---

stages:
  - build
  - deploy

build:
  stage: build
  except:
    - tags
  image:
    name: frankhjung/haskell:9.4.7
    entrypoint: [""]
  variables:
    RTSOPTS: +RTS -N1 -s
    STACK_ROOT: ${CI_PROJECT_DIR}/.stack-work
  script:
    - make clean check build test exec
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
      - .stack-work/
