---

stages:
  - build
  - deploy

build:
  stage: build
  except:
    - tags
  image: frankhjung/haskell:8.6.5
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
      - .stack
      - .stack-work
  variables:
    RTSOPTS: "+RTS -N1"
    STACK_ROOT: "${CI_PROJECT_DIR}/.stack"
  script:
    - make setup clean check build test doc
    - mv $(stack path --local-doc-root) public/
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  only:
    refs:
      - master
  image: alpine:latest
  script:
    - echo Publishing pages ...
  artifacts:
    paths:
      - public
