---

stages:
  - build
  - deploy

build:
  stage: build
  except:
    - tags
  image: frankhjung/haskell:9.0.2
  variables:
    RTSOPTS: "+RTS -N1"
    STACK_ROOT: "${CI_PROJECT_DIR}/.stack"
  script:
    - make clean check build test exec
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .stack/
      - .stack-work/
