---

name: haskell userapp

# yamllint disable-line rule:truthy
on:
  push:
    branches: ['master', 'feature*']
    tags-ignore: ['*']
  check_run:
    types: [rerequested, requested_action]
# yamllint enable

env:
  STACK_ROOT: ${{ github.workspace }}/.stack-work

jobs:

  build:

    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STACK_ROOT }}
          key: ${{ github.ref }}

      - name: build
        run: stack build --pedantic --no-test

      - name: test
        run: stack test --coverage

      - name: exec
        run: stack exec -- main testuser testpassword
